# Generated by Django 5.0.1 on 2024-04-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_plan',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('food_id', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='project_plan',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('project_id', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='routine_plan',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('routine_id', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='sport_plan',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('sport_id', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='task_plan',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('task_id', models.CharField(max_length=45)),
                ('user_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='planner_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='planner_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='planner_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('count', models.CharField(max_length=45)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='planner_app.user')),
            ],
        ),
    ]
