# Generated by Django 5.0.1 on 2024-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0002_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='id_number',
            new_name='id',
        ),
    ]
