# Generated by Django 5.0.1 on 2024-04-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0004_event_delete_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Event_project',
        ),
    ]
