# Generated by Django 5.0.1 on 2024-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0005_rename_event_event_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_project',
            name='description',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
