# Generated by Django 5.0.1 on 2024-04-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0007_alter_event_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
