# Generated by Django 5.0.1 on 2024-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0008_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblevents',
            },
        ),
        migrations.DeleteModel(
            name='food_plan',
        ),
        migrations.DeleteModel(
            name='project_plan',
        ),
        migrations.DeleteModel(
            name='routine_plan',
        ),
        migrations.DeleteModel(
            name='sport_plan',
        ),
        migrations.DeleteModel(
            name='task_plan',
        ),
    ]
