# Generated by Django 5.0.1 on 2024-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0009_events_delete_food_plan_delete_project_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
