# Generated by Django 5.0.1 on 2024-04-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0010_food_end_date_food_end_time_food_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table=None,
        ),
    ]
